<template><DashboardLayout title="Dashboard Guru" role-label="Guru" :navigation="navigation"><section class="welcome"><div><span class="eyebrow-dot dark">Ruang pengajar</span><h2>Selamat datang, {{ user.name || 'Guru' }}.</h2><p>Pantau kelas, tugas, dan perkembangan pembelajaran Anda.</p></div><i class="fas fa-chalkboard-user"></i></section><DashboardMetrics :items="metrics"/><div class="insight"><article><h2>Analisis kompetensi siswa</h2><div class="chart"><canvas ref="chartCanvas"></canvas></div></article><article><h2>Progres kelas</h2><div v-for="item in progress" :key="item.label" class="progress-row"><div><span>{{ item.label }}</span><b>{{ item.value }}%</b></div><div class="bar"><i :style="{ width: `${item.value}%` }"></i></div></div></article></div><section class="head"><h2>Menu pengajaran</h2><p>Akses pekerjaan utama Anda.</p></section><DashboardFeatureGrid :features="features"/></DashboardLayout></template>
<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue'
import Chart from 'chart.js/auto'
import DashboardLayout from '../../components/dashboard/DashboardLayout.vue'
import DashboardMetrics from '../../components/dashboard/DashboardMetrics.vue'
import DashboardFeatureGrid from '../../components/dashboard/DashboardFeatureGrid.vue'
const user=ref(JSON.parse(localStorage.getItem('user')||'{}'));const chartCanvas=ref(null);let chart
const navigation=[{label:'Dashboard',icon:'fas fa-chart-pie',to:'/dashboard/guru'},{label:'Data Kelas',icon:'fas fa-users',to:'/dashboard/guru/kelas'},{label:'Tugas',icon:'fas fa-book-open',to:'/dashboard/guru/tugas'},{label:'Nilai',icon:'fas fa-chart-bar',to:'/dashboard/guru/nilai'}]
const metrics=[{label:'Kelas diampu',value:'4',note:'Tahun ajaran aktif',icon:'fas fa-school',color:'green'},{label:'Total siswa',value:'120',note:'Di semua kelas',icon:'fas fa-users',color:'blue'},{label:'Tugas dinilai',value:'85%',note:'15 tugas menunggu',icon:'fas fa-check-double',color:'amber'},{label:'Kehadiran',value:'98%',note:'Rata-rata minggu ini',icon:'fas fa-calendar-check',color:'red'}]
const features=[{title:'Data Kelas',description:'Lihat siswa dan informasi kelas.',icon:'fas fa-users',to:'/dashboard/guru/kelas'},{title:'Tugas',description:'Buat, periksa, dan nilai tugas siswa.',icon:'fas fa-book-open',to:'/dashboard/guru/tugas'},{title:'Nilai',description:'Kelola nilai dan hasil belajar.',icon:'fas fa-chart-bar',to:'/dashboard/guru/nilai'}];const progress=[{label:'Materi selesai',value:80},{label:'Tingkat kelulusan',value:93},{label:'Keaktifan siswa',value:75}]
onMounted(()=>{chart=new Chart(chartCanvas.value,{type:'radar',data:{labels:['Logika','Kalkulus','Geometri','Statistika','Aljabar'],datasets:[{label:'Kelas X MIPA 1',data:[80,65,75,90,85],backgroundColor:'rgba(28,156,95,.18)',borderColor:'#1c9c5f',pointBackgroundColor:'#1c9c5f'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{r:{suggestedMin:0,suggestedMax:100}}}})});onBeforeUnmount(()=>chart?.destroy())
</script><style scoped>.welcome{background:linear-gradient(110deg,#06231a,#1c9c5f);padding:27px 30px;border-radius:18px;display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.welcome h2{color:#fff;font-size:1.35rem}.welcome p{color:#d9efe0;margin:0}.welcome>i{font-size:3rem;color:#8fd94a}.insight{display:grid;grid-template-columns:2fr 1fr;gap:16px;margin-top:24px}.insight article{padding:22px;background:white;border:1px solid var(--line);border-radius:14px}.insight h2,.head h2{font-size:1.05rem;margin:0 0 16px}.chart{height:260px}.progress-row{margin:19px 0}.progress-row div:first-child{display:flex;justify-content:space-between;font-size:.82rem}.bar{height:9px;background:var(--line);border-radius:99px;overflow:hidden;margin-top:7px}.bar i{display:block;height:100%;background:linear-gradient(90deg,#1c9c5f,#8fd94a);border-radius:99px}.head{margin:32px 0 15px}.head p{font-size:.82rem;margin:3px 0}@media(max-width:850px){.insight{grid-template-columns:1fr}}</style>
