<template>
  <DashboardLayout :title="`Kelola ${label}`" role-label="Admin" :navigation="navigation">
    <div class="toolbar"><div><h2>{{ label }}</h2><p>Data tersimpan di database dan langsung tampil pada halaman publik.</p></div><button class="btn btn-primary" @click="startCreate"><i class="fas fa-plus"></i> Tambah Berita</button></div>
    <p v-if="error" class="alert alert-danger">{{ error }}</p>
    <form v-if="editing" class="editor" @submit.prevent="save">
      <div class="form-row"><div class="form-group"><label>Judul</label><input v-model.trim="form.title" required class="input" placeholder="Judul berita"></div><div class="form-group"><label>Kategori</label><select v-model="form.category" class="select"><option>Umum</option><option>Akademik</option><option>Kegiatan</option><option>Prestasi</option></select></div></div>
      <div class="form-group"><label>Ringkasan</label><textarea v-model.trim="form.excerpt" class="input" rows="2" placeholder="Kosongkan agar dibuat otomatis dari isi berita"></textarea></div><div class="form-group"><label>Isi berita</label><textarea v-model.trim="form.content" required class="input" rows="6"></textarea></div><div class="form-row"><div class="form-group"><label>URL gambar</label><input v-model.trim="form.image" class="input" placeholder="https://..."></div><div class="form-group check"><label><input v-model="form.is_published" type="checkbox"> Publikasikan sekarang</label></div></div>
      <div class="form-actions"><button class="btn btn-ghost" type="button" @click="editing=false">Batal</button><button class="btn btn-primary" :disabled="saving">{{ saving ? 'Menyimpan...' : 'Simpan' }}</button></div>
    </form>
    <div v-if="loading" class="empty">Memuat berita...</div><div v-else class="table-wrap"><table class="data-table"><thead><tr><th>Berita</th><th>Kategori</th><th>Status</th><th>Diperbarui</th><th>Aksi</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td><b>{{ item.title }}</b><br><small>{{ item.excerpt }}</small></td><td>{{ item.category }}</td><td><span class="badge" :class="item.is_published ? 'badge-green' : 'badge-amber'">{{ item.is_published ? 'Terbit' : 'Draf' }}</span></td><td>{{ formatDate(item.updated_at) }}</td><td><button class="action" @click="startEdit(item)">Edit</button><button class="action danger" @click="remove(item.id)">Hapus</button></td></tr><tr v-if="!items.length"><td colspan="5" class="empty">Belum ada berita.</td></tr></tbody></table></div>
  </DashboardLayout>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import DashboardLayout from '../../components/dashboard/DashboardLayout.vue'
import api from '../../utils/api'
const route=useRoute();const label=computed(()=>route.params.resource==='berita'?'Berita':'Pengumuman');const items=ref([]);const loading=ref(false);const saving=ref(false);const error=ref('');const editing=ref(false);const form=ref({});const navigation=[{label:'Dashboard',icon:'fas fa-chart-pie',to:'/dashboard/admin'},{label:'Kelola Berita',icon:'fas fa-newspaper',to:'/dashboard/admin/berita'},{label:'Kelola Pengumuman',icon:'fas fa-bullhorn',to:'/dashboard/admin/pengumuman'}]
const emptyForm=()=>({id:null,title:'',excerpt:'',content:'',image:'',category:'Umum',is_published:true});const fetchItems=async()=>{loading.value=true;error.value='';try{const response=await api.get('/berita');items.value=response.data.data??[]}catch{error.value='Gagal memuat berita dari database.'}finally{loading.value=false}};const startCreate=()=>{form.value=emptyForm();editing.value=true};const startEdit=(item)=>{form.value={...item};editing.value=true};const save=async()=>{saving.value=true;error.value='';try{const payload={...form.value};delete payload.id;const response=form.value.id?await api.put(`/berita/${form.value.id}`,payload):await api.post('/berita',payload);const saved=response.data.data;items.value=form.value.id?items.value.map(item=>item.id===saved.id?saved:item):[saved,...items.value];editing.value=false}catch(err){error.value=err.response?.data?.message||'Berita gagal disimpan.'}finally{saving.value=false}};const remove=async(id)=>{if(!window.confirm('Hapus berita ini?'))return;try{await api.delete(`/berita/${id}`);items.value=items.value.filter(item=>item.id!==id)}catch{error.value='Berita gagal dihapus.'}};const formatDate=(value)=>value?new Date(value).toLocaleDateString('id-ID'):'-';onMounted(fetchItems)
</script>
<style scoped>.toolbar{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:20px}.toolbar h2{font-size:1.2rem;margin:0}.toolbar p{font-size:.84rem;margin:3px 0}.editor{background:#fff;border:1px solid var(--line);border-radius:14px;padding:22px;margin-bottom:20px}.form-actions{display:flex;justify-content:flex-end;gap:9px}.check{display:flex;align-items:center}.check label{margin:0}.action{border:0;background:none;color:var(--leaf-600);font-weight:600;cursor:pointer;margin-right:11px}.action.danger{color:var(--red)}small{color:var(--muted)}.empty{text-align:center;color:var(--muted);padding:24px}@media(max-width:600px){.toolbar{align-items:flex-start;flex-direction:column}}</style>
