<template><DashboardLayout title="Dashboard Admin" role-label="Admin" :navigation="navigation"><section class="welcome"><div><span class="eyebrow-dot dark">Pusat kendali sekolah</span><h2>Semua operasional sekolah dalam satu layar.</h2><p>Kelola data akademik, pengguna, PPDB, serta konten publik dengan cepat.</p></div><i class="fas fa-shield-halved"></i></section><DashboardMetrics :items="metrics"/><section class="head"><h2>Manajemen sistem</h2><p>14 fitur utama untuk administrator.</p></section><DashboardFeatureGrid :features="features"/></DashboardLayout></template>
<script setup>
import DashboardLayout from '../../components/dashboard/DashboardLayout.vue'
import DashboardMetrics from '../../components/dashboard/DashboardMetrics.vue'
import DashboardFeatureGrid from '../../components/dashboard/DashboardFeatureGrid.vue'
const adminItems=[['Kelola User','fas fa-users','akun pengguna'],['Kelola Siswa','fas fa-user-graduate','data siswa'],['Kelola Guru','fas fa-chalkboard-user','data guru'],['Kelola Karyawan','fas fa-id-card','data karyawan'],['Kelola Kelas','fas fa-school','kelas'],['Kelola Mata Pelajaran','fas fa-book-open','mata pelajaran'],['Kelola Ujian','fas fa-file-circle-check','ujian'],['Kelola Soal','fas fa-list-ol','soal'],['Kelola Pendaftaran','fas fa-clipboard-list','pendaftaran'],['Kelola Berita','fas fa-newspaper','berita'],['Kelola Pengumuman','fas fa-bullhorn','pengumuman'],['Kelola Sistem','fas fa-gears','sistem'],['Laporan','fas fa-chart-line','laporan']]
const navigation=[{label:'Dashboard',icon:'fas fa-chart-pie',to:'/dashboard/admin'},...adminItems.map(([label,icon,slug])=>({label,icon,to:`/dashboard/admin/${slug}`}))]
const metrics=[{label:'Total siswa',value:'300',note:'Siswa aktif',icon:'fas fa-user-graduate',color:'green'},{label:'Total guru',value:'50',note:'Tenaga pengajar',icon:'fas fa-chalkboard-user',color:'blue'},{label:'Karyawan',value:'20',note:'Staf aktif',icon:'fas fa-id-card',color:'amber'},{label:'Pendaftaran baru',value:'36',note:'Perlu ditinjau',icon:'fas fa-clipboard-list',color:'red'}]
const features=adminItems.map(([title,icon,slug])=>({title,icon,description:`Kelola ${title.replace('Kelola ','').toLowerCase()} sekolah.`,to:`/dashboard/admin/${slug}`}))
</script><style scoped>.welcome{background:linear-gradient(110deg,#06231a,#1c9c5f);padding:27px 30px;border-radius:18px;display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.welcome h2{color:#fff;font-size:1.35rem}.welcome p{color:#d9efe0;margin:0}.welcome>i{font-size:3rem;color:#8fd94a}.head{margin:34px 0 15px}.head h2{font-size:1.1rem;margin:0}.head p{font-size:.82rem;margin:3px 0}</style>
