<?php
namespace App\Http\Controllers\Api\Admin;
use App\Http\Controllers\Controller; use App\Models\{Guru,Karyawan,Murid,User}; use Illuminate\Http\{JsonResponse,Request}; use Illuminate\Support\Facades\{DB,Hash,Validator}; use Illuminate\Validation\Rule;
class UserController extends Controller {
 private const ROLES=['Admin','Guru','Murid','Karyawan'];
 public function index():JsonResponse { return response()->json(['success'=>true,'data'=>User::with(['guru','murid.kelas','karyawan'])->latest()->get()->map(fn($u)=>$this->out($u))]); }
 public function show(User $user):JsonResponse { return response()->json(['success'=>true,'data'=>$this->out($user->load(['guru','murid.kelas','karyawan']))]); }
 public function store(Request $r):JsonResponse { $d=$this->data($r); DB::transaction(function()use(&$u,$d){$u=User::create(['name'=>$d['name'],'email'=>$d['email'],'password'=>Hash::make($d['password']),'role'=>$d['role'],'is_active'=>$d['is_active']??true]);$this->profile($u,$d);}); return response()->json(['success'=>true,'message'=>'User berhasil dibuat.','data'=>$this->out($u->fresh()->load(['guru','murid.kelas','karyawan']))],201); }
 public function update(Request $r,User $user):JsonResponse { abort_if($r->user()->is($user)&&$r->filled('role')&&strcasecmp($r->role,$user->role)!==0,422,'Anda tidak dapat mengubah role akun sendiri.');$d=$this->data($r,$user,false);$target=$d['role']??$user->role;DB::transaction(function()use($r,$user,$d,$target){if(strcasecmp($target,$user->role)!==0){$this->movable($user);$this->dropProfile($user);$user->update(['role'=>$target]);$this->profile($user,$d);} $a=array_filter(['name'=>$d['name']??null,'email'=>$d['email']??null,'is_active'=>$d['is_active']??null],fn($v)=>$v!==null);if($r->filled('password'))$a['password']=Hash::make($d['password']);$user->update($a);});return response()->json(['success'=>true,'message'=>'User berhasil diperbarui.','data'=>$this->out($user->fresh()->load(['guru','murid.kelas','karyawan']))]); }
 public function resetPassword(Request $r,User $user):JsonResponse {$d=Validator::make($r->all(),['password'=>['required','string','min:8','confirmed']])->validate();$user->update(['password'=>Hash::make($d['password'])]);$user->tokens()->delete();return response()->json(['success'=>true,'message'=>'Password user berhasil direset.']);}
 public function destroy(Request $r,User $user):JsonResponse {abort_if($r->user()->is($user),422,'Anda tidak dapat menghapus akun sendiri.');$user->delete();return response()->json(['success'=>true,'message'=>'User berhasil dihapus.']);}
 private function data(Request $r,?User $u=null,bool $new=true):array {$role=ucfirst(strtolower($r->input('role',$u?->role??'Admin')));$rules=['name'=>[$new?'required':'sometimes','string','max:255'],'email'=>[$new?'required':'sometimes','email',Rule::unique('users','email')->ignore($u?->id)],'password'=>[$new?'required':'nullable','string','min:8'],'role'=>[$new?'required':'sometimes',Rule::in(self::ROLES)],'is_active'=>['nullable','boolean']];$needsProfile=$new||($r->filled('role')&&strcasecmp($role,$u?->role??'')!==0);if($needsProfile&&$role==='Guru')$rules['nip']=['required','string',Rule::unique('gurus','nip')];if($needsProfile&&$role==='Murid'){$rules['nis']=['required','string',Rule::unique('murids','nis')];$rules['gender']=['required',Rule::in(['L','P'])];$rules['tanggal_lahir']=['required','date'];$rules['kelas_id']=['nullable','exists:kelas,id'];}if($needsProfile&&$role==='Karyawan')$rules['bagian']=['required','string','max:100'];return Validator::make($r->all(),$rules)->validate();}
 private function profile(User $u,array $d):void {if($u->role==='Guru')Guru::create(['user_id'=>$u->id,'nip'=>$d['nip'],'nama_lengkap_guru'=>$u->name]);if($u->role==='Murid'){$m=Murid::create(['user_id'=>$u->id,'nis'=>$d['nis'],'Nama_lengkap_murid'=>$u->name,'gender'=>$d['gender'],'tanggal_lahir'=>$d['tanggal_lahir'],'kelas_id'=>$d['kelas_id']??null]);$m->setAttribute('Nama_lengkap_murid',$u->name);$m->save();}if($u->role==='Karyawan')Karyawan::create(['user_id'=>$u->id,'nip'=>$d['nip']??null,'nama_lengkap_karyawan'=>$u->name,'bagian'=>$d['bagian']??null]);}
 private function movable(User $u):void {if($u->guru&&($u->guru->jadwals()->exists()||$u->guru->subjekgurus()->exists()||$u->guru->tugas()->exists()))abort(422,'Role tidak dapat diubah karena profil guru masih memiliki data akademik.');if($u->murid&&($u->murid->pengumpulanTugas()->exists()||$u->murid->tagihanSpps()->exists()))abort(422,'Role tidak dapat diubah karena profil murid masih memiliki data terkait.');if($u->karyawan&&$u->karyawan->slipGajis()->exists())abort(422,'Role tidak dapat diubah karena profil karyawan masih memiliki slip gaji.');}
 private function dropProfile(User $u):void {$u->guru?->delete();$u->murid?->delete();$u->karyawan?->delete();}
 private function out(User $u):array{return ['id'=>$u->id,'name'=>$u->name,'email'=>$u->email,'role'=>$u->role,'is_active'=>(bool)$u->is_active,'profile'=>$u->guru??$u->murid??$u->karyawan];}
}
